default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 2 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  post: 5432
  database: askme
  username: askme
  password: askme

development:
  <<: *default
  database: askme_dev
  password: askme_pwd

test:
  <<: *default
  database: askme_test

production:
  <<: *default
  database: askme
